#!/bin/sh
# TEMP shortcut to quickly enable dev-tool plugins
# usage: ./enable-dev-tools <server substring>

haplo-plugin -p std_workflow,std_workflow_dev,std_document_store,std_document_store_dev -s $1 --force
